### ISSUE TITLE
inquiry

### ISSUE THREAD

**Issue by abubakerSherif** [phako/BPM#1]
Hi,

First thanks for your effort and I am really appreciating your work.

May I know which model of Microlife BPA you used in this project ? 

thank you so much !

**Comment by phako** [comment]
I got a rebranded version called "Aponorm Blutdruckmessgerät Oberarm Professionell")

I think it is the BP A6 PC https://www.microlife.com/support/blood-pressure/bp-a6-pc

**Comment by phako** [comment]
I updated the Read me with this information :)
